apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/akuity/kargo-advanced.git
      revision: HEAD
      directories:
      - path: env/*
  template:
    metadata:
      name: guestbook-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-advanced:*
    spec:
      destination:
        namespace: guestbook-{{path.basename}}
        # Specify either a cluster destination name or server address:
        # name: REPLACEME
        # server: https://REPLACEME
      project: guestbook
      source:
        path: app # default render path
        repoURL: https://github.com/akuity/kargo-advanced.git
        targetRevision: env/{{path.basename}}